# Generated by Django 5.2.1 on 2025-06-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
